### ISSUE TITLE
requests: Emit sentry warning if a response contains a `Sunset` or `Deprecated-Usage` header.

### ISSUE THREAD

**Issue by underyx** [kiwicom/kiwi-platform-py#4]
- The `Sunset` header is documented here nicely: https://tools.ietf.org/html/rfc8594
   - Upon seeing it we should send a warning to Sentry with the sunset date and linked informational URL from this header: `Link: <http://example.net/sunset>;rel="sunset";type="text/html"`
- The `Deprecated-Usage` would be our own custom header which just has a plain text value which is copied to a Sentry warning. The main difference here is that the `Sunset` standard is for deprecated URLs, while this is for any kind of deprecated behavior (such as using old parameter names.)

**Comment by paveldedik** [comment]
Are we going to support both `sentry_sdk` and older `raven`? I'm not sure how to do this as we probably don't want to have too many dependencies. We could do something like:

```python
try:
    from raven import Client
    client = Client(os.getenv("SENTRY_DSN"))
    capture_exception = client.captureException
except ImportError:
    from sentry_sdk import capture_exception
```

And have the sentry_sdk/raven dependencies only as optional extras?

The problem is still this won't use project's own custom sentry/logging handlers. And it also requires the `SENTRY_DSN` env variable.

If we only need to support `sentry_sdk`, it should not be really a problem as we just import the `capture_exception` function.

**Comment by underyx** [comment]
I'd support only `sentry_sdk` I think 😇

Sent via Superhuman ( https://sprh.mn/?vip=bence@kiwi.com )
